### ISSUE TITLE
server kadang bisa & tidak

### ISSUE THREAD

**Issue by fauzanabid** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-menantu_idaman#1]

**Comment by arinanda** [comment]
untuk servernya kami menggunakan pc kami sendiri yang kemudian kami tunneling menggunakan ssh. kekurangan dari ssh ini adalah koneksi akan otomatis terminated setelah melalui selang beberapa waktu. solusi untuk hal ini adalah menggunakan autossh yang sedang kami usahakan untuk segera bisa digunakan agar lebih stabil dan bisa digunakan secara terus menerus. mohon maaf atas ketidaknyamanannya 🙏
