### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by vickymahfudy** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-menantu_idaman#2]
Apakah server deploy nya memang tidak stabil? Karena sering hilang koneksi ketika memanggil API nya

**Comment by arinanda** [comment]
untuk servernya kami menggunakan pc kami sendiri yang kemudian kami tunneling menggunakan ssh. kekurangan dari ssh ini adalah koneksi akan otomatis terminated setelah melalui selang beberapa waktu. solusi untuk hal ini adalah menggunakan autossh yang sedang kami usahakan untuk segera bisa digunakan agar lebih stabil dan bisa digunakan secara terus menerus. mohon maaf atas ketidaknyamanannya 🙏
